### ISSUE TITLE
Cannot find libwinpthread-1.dll

### ISSUE THREAD

**Issue by lukefchou** [vegarringdal/rvm_parser_glb#2]
I tried to execute the rvm_parse using the release 0.0.2. It prompts that the libwinpthread-1.dll cannot be find. 
How can I fix it?

**Comment by vegarringdal** [comment]
Thx for giving it a try 😁

I need to improve cmakelist.txt to ensure static linking
I prb need to add lpthread.
Might get time in the weekend.

3 workaround until I do this. 
* install mingw-64 as readme shows for vscode 
* use visual studio and compile new version
* use linux version, by running it in wsl2

**Comment by lukefchou** [comment]
Thanks for your prompt reply.
I also find that the color is not exported correctly. The rvmparser project
has the same issue.

Vegar Ringdal ***@***.***> 于2024年9月13日周五 14:12写道：

**Comment by vegarringdal** [comment]
Do you have a sample file with the color issue ?
might be able to fix it

**Comment by vegarringdal** [comment]
@lukefchou 

File you had color issues with, did it say `Using default colors, not support for COLR block` when you used the parser ?
